### ISSUE TITLE
(Feature request) Test against multiple servers

### ISSUE THREAD

**Issue by anuragbhatia** [frdmn/docker-speedtest-grafana#12]
Please consider adding a feature where we can define multiple speed test server and it tests against those sequentially. One can define the speed test server using the ID. 

I would love to have a test report from a couple of servers in India, Europe, US and Singapore.

**Comment by n1nj4888** [comment]
Why not just run multiple containers each with a different SPEEDTEST_HOST and SPEEDTEST_SERVER but all pointing to the same InfluxDB?

**Comment by anuragbhatia** [comment]
The problem in doing that would be - all speed test instance would run at the same time, will choke the pipe and will lead to inconsistent results. If running one after other then we know for sure that only one test is running a given time.

**Comment by frdmn** [comment]
You could add some delays in addition:

```
version: '2'

services:
  speedtest1:
    restart: always
    image: frdmn/speedtest-grafana:latest
    command: sh -c "
      sleep 300 &&
      node index.js"

  speedtest2:
    restart: always
    image: frdmn/speedtest-grafana:latest
    command: sh -c "
      sleep 600 &&
      node index.js"

```
