### ISSUE TITLE
Add "How to change speedtest interval" to README

### ISSUE THREAD

**Issue by gleniat** [frdmn/docker-speedtest-grafana#16]
This is how docker-compose.yml looks like:

```
speedtest:
    restart: always
    image: frdmn/speedtest-grafana:latest
    container_name: speedtest
    environment:
      - "SPEEDTEST_INTERVAL=${SPEEDTEST_SPEEDTEST_INTERVAL}"
      - "SPEEDTEST_HOST=${SPEEDTEST_HOST}"
    depends_on:
      - influxdb
```

1. Where does ${SPEEDTEST_SPEEDTEST_INTERVAL} come from? (.env file?)
2. How can I change the values while running via docker-compose up? Is it possible to change the interval without stopping and deleting everything and (with edited .env file) starting from scratch?

Great work by the way
Thanks
